title: Seismic Data Processes
description: Some basic steps to prepare and run the earthquake source mechanism program-gcap, micro-seismic detection, location, and AI-driven processes.
email: mensanli@163.com
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
